### ISSUE TITLE
Support for `oil.nvim`

### ISSUE THREAD

**Issue by lukealvoeiro** [alexpasmantier/pymple.nvim#30]
Awesome job on the plugin!! Currently this does not work for Oil - that is the only blocker for adoption for me.

**Comment by alexpasmantier** [comment]
Thanks for the feedback, very appreciated.
I'm planning on adding support for oil very soon. 
Will update this issue as soon as it's in production.
Cheers

**Comment by alexpasmantier** [comment]
There you go 😊

**Comment by lukealvoeiro** [comment]
Thank you so much! 🥳
