### ISSUE TITLE
Getting this error before nvim starts

### ISSUE THREAD

**Issue by razak17** [alexpasmantier/pymple.nvim#40]
![2024-09-10_221256_726099152](https://github.com/user-attachments/assets/5ce48299-36d1-4f91-aae7-09b5297064c5)

Based on the little investigating I did, it seems to be coming from the this line in log.lua

![2024-09-10_221548_426287532](https://github.com/user-attachments/assets/cc3c7e79-dba2-45b5-a7e4-9de673f1b9a8)

**Comment by alexpasmantier** [comment]
Did this resolve on its own?

I'm guessing it's due to some interaction with another plugin (typically a session management plugin) since Pymple doesn't run anything by default on start.
