### ISSUE TITLE
Should it work on windows ?!

### ISSUE THREAD

**Issue by bro69noscope** [alexpasmantier/pymple.nvim#48]
Hey, getting this error when trying to use the plugin: 
<details>

```
 
   Error  21:19:10 notify.error lazy.nvim Failed to run `config` for pymple.nvim

...Data/Local/nvim-data/lazy/pymple.nvim/lua/pymple/log.lua:40: attempt to compare number with nil

# stacktrace:
  - pymple.nvim\lua\pymple\log.lua:40 _in_ **maybe_trim_logfile**
  - pymple.nvim\lua\pymple\log.lua:59 _in_ **new**
  - pymple.nvim\lua\pymple\init.lua:32 _in_ **setup**
  - pymple.nvim\lua\pymple\init.lua:60 _in_ **setup**
  - ~/AppData/Local/nvim/lua/plugins/pymple.lua:13 _in_ **config**
  - ~\AppData\Local\nvim/lua/config/lazy.lua:17
  - ~\AppData\Local\nvim\init.lua:2

```

</details>

I had to manually add two missing deps with cargo too (`log`, and `winapi-util`) dunno if related

EDIT: If I copy paste the default config setup the error changes to:
<details>

```
   Error  21:30:42 notify.error lazy.nvim Failed to run `config` for pymple.nvim

...Data/Local/nvim-data/lazy/pymple.nvim/lua/pymple/log.lua:140: attempt to index local 'fp' (a nil value)

# stacktrace:
  - pymple.nvim\lua\pymple\log.lua:140 _in_ **info**
  - pymple.nvim\lua\pymple\init.lua:33 _in_ **setup**
  - pymple.nvim\lua\pymple\init.lua:60 _in_ **setup**
  - lua/plugins/pymple.lua:13 _in_ **config**
  - lua/config/lazy.lua:17
  - init.lua:2
  ```
</details>
  
  EDIT 2: disabling file logging fixes the above errors, but another error is raised:
  
  `   Error  21:33:57 notify.error [Neo-tree ERROR] Error in event handler for event file_moved[table: 0x015bc1401900]: ...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
`

**Comment by alexpasmantier** [comment]
Hi, thanks for the issue.

In the current state of things, the plug-in will only work on unix-based systems. 

I believe making it compatible with windows isn't a huge amount of work since it would primarily consist in making path separators OS-agnostic. 

If you're willing to make such a change feel free to open a PR. I might work on that at some point but it's not the top prio for now.

**Comment by bro69noscope** [comment]
Ok, might try but I'm a total noob although it could be interesting for a first contribution

**Comment by ilovevim** [comment]
My Win10 platform with Neovim 0.11 pose the same error, which says:

Error executing Lua callback: ...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:248: ENOENT: no such file or directory: "/bin/sh"
stack traceback:
	[C]: in function 'error'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:248: in function 'spawn'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:353: in function 'system'
	...ata/Local/nvim-data/lazy/pymple.nvim/lua/pymple/jobs.lua:98: in function 'gg'
	...data/lazy/pymple.nvim/lua/pymple/update_imports/init.lua:17: in function 'make_split_imports_job'
	...data/lazy/pymple.nvim/lua/pymple/update_imports/init.lua:67: in function 'prepare_jobs'
	...Data/Local/nvim-data/lazy/pymple.nvim/lua/pymple/api.lua:122: in function 'update_imports'
	.../nvim-data/lazy/pymple.nvim/lua/pymple/user_commands.lua:14: in function <.../nvim-data/lazy/pymple.nvim/lua/pymple/user_commands.lua:9>
