### ISSUE TITLE
Resolve import under cursor not returning imports even though it seems to be finding them

### ISSUE THREAD

**Issue by dimtsi** [alexpasmantier/pymple.nvim#55]
First of all great job!! :D :D  This is one of the most important missing components for Python development in NeoVim.

The `resolve-import-under-cursor` option at the moment cannot resolve modules that exist in the running conda environment and have never been imported in the project yet. Would this be sth that could be supported? The path to the running Conda Env can be found using the `CONDA_PREFIX` environment variable.

Again, kudos to the amazing work!! :) :)

**Comment by dimtsi** [comment]
Upon looking a bit further I discovered that the issue does not seem to be related to support for conda environments as the plugin is looking into the relevant sys paths. I can see that the module is somewhat found but still I get the `No results in the current environment` message. 

In the below example I just want to import the `databricks.sdk.WorkspaceClient`. After running the `resolve-import-under-cursor` and setting pymple logger to Debug I am seeing the following logs:

![image](https://github.com/user-attachments/assets/c7b8797b-bb9d-4a98-ad09-296d94362869)

It seems that the plugin is finding the relevant import as a candidate but still not returning it. I am having the same issue with less "exotic" packages such as stdlib packages

**Comment by alexpasmantier** [comment]
Hi, thanks for the feedback.

Could you try udpating pymple to its latest version, try the resolve import feature again and tell me if you still get that behavior ?

**Comment by dimtsi** [comment]
@alexpasmantier At first glance the feature seems to be working correctly now! :) 

Thanks for the quick response and update! 

Great job once again!!
